name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.3.0
        uses: actions/setup-node@v1
        with:
          node-version: "16.3.0"
      - name: Install Packages
        run: yarn install
      - name: Validate typescript
        run: yarn validate-ts
      - name: Run unit tests
        run: yarn test:unit
      - name: Build app
        run: yarn build